### ISSUE TITLE
[BUG] MENU NOT WORKING

### ISSUE THREAD

**Issue by Mikxsh** [RatPoison-dev/RatPoison#829] opened 2021-07-16 15:22 UTC
MENU NOT WORKING

After about 2 months I now came back and downloaded the latest version 1.7.1.3 and when launching the menu fails each time to successfully open and run into an error.

Please kindly help.

![Capture](https://user-images.githubusercontent.com/87537370/125970945-19d80793-a9b8-41f7-a07a-7597247d2e2e.PNG)

**Comment by sotakoira** [comment] 2021-07-16 15:27
duplicate of:

#813

**Closed** 2021-07-16 16:04 UTC
